<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\PageContent;
use App\Models\Product;
use App\Models\SiteSetting;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // ── 1. SUPER ADMIN USER ──
        User::updateOrCreate(
            ['email' => 'admin@recoltenails.com'],
            [
                'name' => 'Récolte Atelier Admin',
                'password' => Hash::make('RecolteAdmin2026!'),
                'is_admin' => true,
            ]
        );

        // ── 2. SITE SETTINGS ──
        $settings = [
            'site_name' => 'Récolte Nails Paris',
            'tagline' => 'Paris • Haute Nail Couture & Organic Care',
            'whatsapp_number' => '917016266727',
            'phone' => '+91 7016266727',
            'email' => 'atelier@recoltenails.com',
            'address' => '24 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
            'consultation_hours' => '9:00 AM – 6:30 PM (Mon – Sat)',
            'announcement_bar' => '✨ Complimentary Luxury Sizing Prep Kit with Every Order • Handcrafted in Paris & Express Studio Delivery',
            'instagram_url' => 'https://www.instagram.com/recolte_gelpolish/',
            'instagram_handle' => '@recolte_gelpolish',
            'tiktok_url' => 'https://tiktok.com/@recoltenails',
            'pinterest_url' => 'https://pinterest.com/recoltenails',
            'footer_bio' => 'Récolte Nails is a Parisian haute nail couture house specializing in salon-grade Japanese gel polishes, builder gels, and professional nail art systems for salon luxury at home.',
            'copyright' => '© 2026 Récolte Nails Paris. All rights reserved. Handcrafted with Japanese salon gels.'
        ];

        foreach ($settings as $key => $val) {
            SiteSetting::updateOrCreate(['key' => $key], ['value' => $val]);
        }

        // ── 3. 21 CATEGORIES (MATCHING DRIVE FILTER FOLDERS) ──
        $categories = [
            [
                'name' => 'Base Coat',
                'slug' => 'base-coat',
                'icon_emoji' => '🛡️',
                'description' => 'Superior adhesion base coats designed to protect natural nails and prevent lifting for 4+ weeks.',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'BIAB',
                'slug' => 'biab',
                'icon_emoji' => '💧',
                'description' => 'Builder In A Bottle liquid gels for natural nail overlays, apex building, and extreme strength.',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Blooming Gel',
                'slug' => 'blooming-gel',
                'icon_emoji' => '🌸',
                'description' => 'Fast-spreading bloom gels creating effortless marble, watercolor, and botanical floral nail art.',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Builder Gel',
                'slug' => 'builder-gel',
                'icon_emoji' => '✨',
                'description' => 'High-viscosity sculpting gels for durable extensions, apex building, and structural reinforcement.',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Carving Gel',
                'slug' => 'carving-gel',
                'icon_emoji' => '🏺',
                'description' => '3D moldable non-sticky carving gels for sculpted relief nail art, figurines, and emboss florals.',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Cat Eye Gels',
                'slug' => 'cat-eye-gels',
                'icon_emoji' => '👁️',
                'description' => 'Magnetic chameleon and velvet cat eye gels with celestial refractive shimmer and deep galactic luster.',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Gel Polishes',
                'slug' => 'gel-polishes',
                'icon_emoji' => '🎨',
                'description' => 'Master salon gel polish collections with single-stroke opacity, self-leveling viscosity, and 4+ weeks wear.',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Matte Top Coat',
                'slug' => 'matte-top-coat',
                'icon_emoji' => '🌫️',
                'description' => 'Cashmere-smooth velvety matte top coats with non-wipe formula and anti-scratch finish.',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Metallic Gel',
                'slug' => 'metallic-gel',
                'icon_emoji' => '🪞',
                'description' => 'Liquid mirror chrome and molten metallic gels for high-definition line art and chrome accents.',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'Mixing Gel',
                'slug' => 'mixing-gel',
                'icon_emoji' => '🧪',
                'description' => 'Crystal-clear dilution and blending gels for custom gradients, glitters, and ombré shading.',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'Painting Gel',
                'slug' => 'painting-gel',
                'icon_emoji' => '🖌️',
                'description' => 'Ultra-pigmented fine art painting gels designed for precision linework and detailing.',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'Platinum Gel',
                'slug' => 'platinum-gel',
                'icon_emoji' => '⭐',
                'description' => 'High-density micro-foil and platinum glitter gels delivering maximum diamond sparkle.',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'name' => 'Polygel',
                'slug' => 'polygel',
                'icon_emoji' => '💎',
                'description' => 'Hybrid acrylic-gel formula offering featherweight feel with unbreakable strength.',
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'name' => 'Primer',
                'slug' => 'primer',
                'icon_emoji' => '🧴',
                'description' => 'Acid-free dehydrating bonding primers maximizing gel longevity without natural nail damage.',
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Reflective Polish',
                'slug' => 'reflective-polish',
                'icon_emoji' => '✨',
                'description' => 'Disco flash reflective glitter gels illuminating with blinding brilliance under direct flash.',
                'sort_order' => 15,
                'is_active' => true,
            ],
            [
                'name' => 'Rhinestone Gel',
                'slug' => 'rhinestone-gel',
                'icon_emoji' => '💍',
                'description' => 'Extra-strong no-wipe crystal adhesive gel securing gems, pearls, and charms firmly.',
                'sort_order' => 16,
                'is_active' => true,
            ],
            [
                'name' => 'Rubber Base',
                'slug' => 'rubber-base',
                'icon_emoji' => '🌿',
                'description' => 'Flexible 5-in-1 rubber bases providing shock absorption and leveling for brittle nails.',
                'sort_order' => 17,
                'is_active' => true,
            ],
            [
                'name' => 'Solid Glue Gel',
                'slug' => 'solid-glue-gel',
                'icon_emoji' => '🏷️',
                'description' => 'Solid adhesive gels for press-on tips and soft gel extensions with zero air bubbles.',
                'sort_order' => 18,
                'is_active' => true,
            ],
            [
                'name' => 'Spider Gel',
                'slug' => 'spider-gel',
                'icon_emoji' => '🕸️',
                'description' => 'Elastic matrix spider gels pulling crisp geometric lines and spiderweb nail art in seconds.',
                'sort_order' => 19,
                'is_active' => true,
            ],
            [
                'name' => 'Top Coats',
                'slug' => 'top-coats',
                'icon_emoji' => '💎',
                'description' => 'Glass-like high shine tempered top coats providing scratch-resistant long-lasting protection.',
                'sort_order' => 20,
                'is_active' => true,
            ],
            [
                'name' => '6-in-1 Top Coat',
                'slug' => '6-in-1-top-coat',
                'icon_emoji' => '👑',
                'description' => 'Diamond-hard multifunctional top coat engineered for sealing, leveling, and extreme durability.',
                'sort_order' => 21,
                'is_active' => true,
            ],
        ];

        $newCatSlugs = array_column($categories, 'slug');
        Category::whereNotIn('slug', $newCatSlugs)->delete();

        foreach ($categories as $cat) {
            Category::updateOrCreate(['slug' => $cat['slug']], $cat);
        }

        $catMap = Category::pluck('id', 'name')->toArray();

        // ── 4. PRODUCTS (MATCHING DRIVE FILTER FOLDERS & MEDIA) ──
        $products = [
            [
                'title' => 'Récolte Excellent Base Coat',
                'slug' => 'recolte-excellent-base-coat',
                'category' => 'Base Coat',
                'category_id' => $catMap['Base Coat'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.98,
                'reviews_count' => 196,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => '60 Days+ Strong Adhesion Natural Resin Base Coat with Keratin Protection',
                'description' => 'Engineered with high-purity natural tree resins and a purified water-clarified formula, Récolte Excellent Base Coat provides up to 60+ days of unwavering adhesion without chipping or lifting. The acid-free, odorless formulation forms a protective barrier over the natural nail keratin while auto-leveling seamlessly. Easy soak-off in 5–8 minutes with zero natural nail damage.',
                'key_ingredients' => 'Extracted Natural Tree Resin, Purified Deionized Base, Medical-Grade Polyurethane Acrylate, HEMA-Free Photo-Initiators, Keratin Vitamin Shield',
                'how_to_use' => '1. Cleanse and dehydrate natural nail with Récolte Primer. 2. Apply a thin, uniform coat of Excellent Base Coat capping the free edge. 3. Cure for 60 seconds under UV/LED lamp. 4. Follow with your chosen Récolte gel polish.',
                'main_image' => '/uploads/products/catalog/BASE_COAT_base.png',
                'images' => [
                    '/uploads/products/catalog/BASE_COAT_base.png',
                    '/uploads/products/catalog/BASE_COAT_base_top.png',
                    '/uploads/products/catalog/BASE_COAT_base_coat.png',
                    '/uploads/products/catalog/BASE_COAT_base_and_top.png',
                    '/uploads/products/catalog/BASE_COAT_white_bottle_1_.JPG',
                    '/uploads/products/catalog/BASE_COAT_white_bottle_2_.JPG',
                    '/uploads/products/catalog/BASE_COAT_base_coat.mp4',
                ],
                'shades' => [
                    ['name' => 'Crystal Clear Base', 'hex' => '#F4EFEB'],
                ],
                'sizes' => [
                    '15ml Precision Atelier Bottle',
                    '30ml Salon Refill',
                ],
                'benefits' => [
                    '60 Days+ Strong Adhesion Without Lifting',
                    'Extracted Natural Resin & Non-Toxic Formula',
                    'Acid-Free & Odorless Keratin Protection',
                    'Flawless Auto Self-Leveling & Zero Shrinkage',
                    'Easy Soak-Off in 5–8 Minutes',
                    'Anti-Stain, Scratch Resistance & Non-Yellowing',
                ],
                'sort_order' => 1,
            ],
            [
                'title' => 'Récolte BIAB Liquid Builder Gel',
                'slug' => 'recolte-biab-liquid-builder-gel',
                'category' => 'BIAB',
                'category_id' => $catMap['BIAB'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.95,
                'reviews_count' => 127,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => 'Self-leveling liquid builder in a bottle for natural nail overlays & apex strength',
                'description' => 'Récolte BIAB (Builder in a Bottle) offers the ideal balance of brush-on convenience and structural sculpting strength. Its self-leveling formula fills natural ridges, reinforces delicate nails, and allows effortless apex architecture without heat spikes.',
                'key_ingredients' => 'Japanese Oligomer Resin, Micro-Fiber Reinforcing Matrix, Optical Stabilizers',
                'how_to_use' => '1. Apply Récolte Base Coat and cure 60s. 2. Apply a thin slip layer of BIAB, then place a bead near the cuticle and gently guide it towards the free edge to build the apex. 3. Flash cure 10s, then full cure 60s.',
                'main_image' => '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_1_.jpg',
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_2_.jpg',
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_3_.jpg',
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_4_.jpg',
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_5_.jpg',
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_6_.jpg',
                    '/uploads/products/catalog/BIAB_Liquid_Builder_Gel_1_.mp4',
                ],
                'shades' => [
                    ['name' => 'Soft Rose Nude', 'hex' => '#E6C5C0'],
                    ['name' => 'Milky White', 'hex' => '#F7F4F1'],
                    ['name' => 'Clear Glass', 'hex' => '#ECE5DF'],
                ],
                'sizes' => [
                    '15ml Brush-On Bottle',
                    '50ml Studio Jar',
                ],
                'benefits' => [
                    'Effortless Brush-On Application',
                    'Auto Self-Leveling Formula',
                    'Builds Natural Apex & Structure',
                    'Zero Heat Spike Technology',
                ],
                'sort_order' => 25,
            ],
            [
                'title' => 'Récolte Fast-Spread Blooming Gel',
                'slug' => 'recolte-fast-spread-blooming-gel',
                'category' => 'Blooming Gel',
                'category_id' => $catMap['Blooming Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 134,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => 'Instant blooming gel for artistic marble, watercolor bloom & blossom effects',
                'description' => 'Unlock effortless Parisian nail artistry with Récolte Fast-Spread Blooming Gel. Applied wet over cured color, it gently diffuses drops of gel polish into fluid watercolor petals, organic marble veins, and smoke clouds before curing.',
                'key_ingredients' => 'Low Surface-Tension Acrylic Monomers, Optical Diffusion Fluid, UV Curatives',
                'how_to_use' => '1. Apply background color and cure. 2. Apply a thin, uncured layer of Blooming Gel. 3. Dot or line your desired gel polish into the wet surface and watch it bloom into shape. 4. Cure 60s once desired bloom is achieved, then seal with Top Coat.',
                'main_image' => '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_1_.jpg',
                    '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_2_.jpg',
                    '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_3_.jpg',
                    '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_4_.jpg',
                    '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_5_.jpg',
                    '/uploads/products/catalog/BLOOMING_GEL_Blooming_gel_fast_.mp4',
                ],
                'shades' => [
                    ['name' => 'Clear Bloom Base', 'hex' => '#FFFFFF'],
                ],
                'sizes' => [
                    '15ml Studio Bottle',
                ],
                'benefits' => [
                    'Creates Instant Marble & Rose Effects',
                    'Controlled Fluid Diffusion',
                    'Compatible with All Gel Polish Colors',
                    'No Special Brushes Required',
                ],
                'sort_order' => 26,
            ],
            [
                'title' => 'Récolte Sculpting Master Builder Gel',
                'slug' => 'recolte-sculpting-master-builder-gel',
                'category' => 'Builder Gel',
                'category_id' => $catMap['Builder Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.95,
                'reviews_count' => 141,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => 'High-viscosity professional builder gel for long extensions, forms & tip overlays',
                'description' => 'Formulated for salon master nail technicians, Récolte Master Builder Gel features exceptional architectural viscosity that holds its shape without running into lateral sidewalls. Yields glass-clear transparency and extreme impact resistance.',
                'key_ingredients' => 'High-Density Urethane Dimethacrylate, Non-Yellowing Optical Clarifiers, Photo-Curing Resins',
                'how_to_use' => '1. Prep natural nails and apply primer & base coat. 2. Position nail form or tip. 3. Sculpt apex and length with a gel brush. 4. Cure 60-90s under UV/LED. 5. Wipe dispersion layer, file to shape, and seal.',
                'main_image' => '/uploads/products/catalog/BUILDER_GEL_builder_gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_1_.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_1.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_2.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_3-2.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_3.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_4-2.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_4.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_5-2.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_artboard_5.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_1_.png',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_2_.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_2_.png',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_3_.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_3_.png',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_4_.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_5_.jpg',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_6_.png',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_7_.png',
                    '/uploads/products/catalog/BUILDER_GEL_builder_gel_1_.mp4',
                    '/uploads/products/catalog/BUILDER_GEL_video_showcase.mp4',
                ],
                'shades' => [
                    ['name' => 'Crystal Clear', 'hex' => '#FFFFFF'],
                    ['name' => 'Cover Pink', 'hex' => '#E8B4B8'],
                    ['name' => 'Soft White', 'hex' => '#F5F5F0'],
                ],
                'sizes' => [
                    '30ml Atelier Jar',
                    '50ml Master Salon Jar',
                ],
                'benefits' => [
                    'Extra High Viscosity',
                    'Does Not Run into Cuticles',
                    'Rock-Solid Strength & Flexibility',
                    'Crystal Clear Clarity',
                ],
                'sort_order' => 27,
            ],
            [
                'title' => 'Récolte 3D Sculpture Carving Gel',
                'slug' => 'recolte-3d-sculpture-carving-gel',
                'category' => 'Carving Gel',
                'category_id' => $catMap['Carving Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 148,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => 'Non-sticky moldable 3D carving gel for sculpted florals, lace & relief nail art',
                'description' => 'Récolte 3D Carving Gel provides a sculptable clay-like texture that can be rolled, pressed, and shaped with silicone tools or fingers without sticking. Allows unlimited working time to craft ornate floral petals, lace textures, and modern 3D emboss designs.',
                'key_ingredients' => 'Solid Sculpting Oligomers, Silica Micro-Spheres, Fine Cosmetic Pigments',
                'how_to_use' => '1. Take a small bead with a spatula or silicone tool. 2. Roll into desired shape and press onto cured gel manicure. 3. Sculpt petals or relief patterns. 4. Cure for 60 seconds.',
                'main_image' => '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_1_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_2_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_3_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_4_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_5_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_6_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_7_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_8_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_9_.jpg',
                    '/uploads/products/catalog/CARVING_GEL_3D_Carving_Gel_1_.mp4',
                ],
                'shades' => [
                    ['name' => 'Pure White', 'hex' => '#FFFFFF'],
                    ['name' => 'Opal Pearl', 'hex' => '#F2EDE4'],
                    ['name' => 'Noir Velvet', 'hex' => '#1B1817'],
                ],
                'sizes' => [
                    '10g Emboss Pot',
                    '20g Studio Pot',
                ],
                'benefits' => [
                    'Kneadable Non-Sticky Texture',
                    'Holds Intricate 3D Details Without Slumping',
                    'Zero Tack After Curing',
                    'Unlimited Work Time Before UV Cure',
                ],
                'sort_order' => 28,
            ],
            [
                'title' => 'Récolte 24 Shades Cat Eye Gel Polish Kit (A-Series)',
                'slug' => 'recolte-24-shades-cat-eye-gel-polish-kit-a-series',
                'category' => 'Cat Eye Gels',
                'category_id' => $catMap['Cat Eye Gels'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 155,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => '24-shade magnetic velvet cat eye gel polish collection with deep galaxy refraction',
                'description' => 'The A-Series collection encompasses 24 bewitching magnetic jewel tones saturated with rare-earth magnetic micro-prisms. Using the included dual-ended stylus magnet, create velvet glow lines, cosmic halos, and cat-eye light bars in seconds.',
                'key_ingredients' => 'Japanese Acrylate Gel, Micronized Rare-Earth Magnetic Particles, Cosmetic Mica, UV Blockers',
                'how_to_use' => '1. Apply base coat and cure. 2. Apply 1 coat of Récolte Cat Eye gel. 3. Hover magnet 2mm over the wet gel for 5-10 seconds to create desired pattern. 4. Immediately cure 60s. 5. Seal with Top Coat.',
                'main_image' => '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye_4_.jpg',
                'images' => [
                    '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye_4_.jpg',
                    '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye_5_.jpg',
                    '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye_6_.jpg',
                    '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye_7_.jpg',
                    '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_bottle_2_.jpg',
                    '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye.mp4',
                ],
                'shades' => [
                    ['name' => 'Cosmic Emerald', 'hex' => '#184D3B'],
                    ['name' => 'Rose Quartz Velvet', 'hex' => '#D48C9A'],
                    ['name' => 'Amethyst Gaze', 'hex' => '#6C4675'],
                    ['name' => 'Solar Gold', 'hex' => '#C5A880'],
                ],
                'sizes' => [
                    'Full 24-Piece Atelier Kit (15ml each)',
                    'Individual 15ml Bottle',
                ],
                'benefits' => [
                    '24 Vibrant Magnetic Shimmers',
                    'Dual-Action Magnet Compatible',
                    'Velvet & Cat Eye Line Transitions',
                    '4-Week Chip-Free Gloss',
                ],
                'sort_order' => 29,
            ],
            [
                'title' => 'Récolte 10 Shades Cat Eye Gel Polish Kit (E-Series)',
                'slug' => 'recolte-10-shades-cat-eye-gel-polish-kit-e-series',
                'category' => 'Cat Eye Gels',
                'category_id' => $catMap['Cat Eye Gels'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 162,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => '10-shade magnetic glass cat eye gel collection with multi-dimensional depth',
                'description' => 'The E-Series provides 10 ethereal, luminous shades featuring sheer crystalline glass bases paired with ultra-reflective magnetic shimmer. Creates an oceanic depth that shifts dynamically under movement and changing light angles.',
                'key_ingredients' => 'Pure Crystalline Resin, Magnetic Iron Oxides, High-Purity Photoinitiator Blend',
                'how_to_use' => '1. Apply base coat or black base for maximum contrast and cure. 2. Brush on E-Series Cat Eye. 3. Manipulate magnetic shimmer with styling wand. 4. Cure 60 seconds.',
                'main_image' => '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_1_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_10_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_11_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_12_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_13_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_14_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_15_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_16_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_17_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_18_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_19_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_20_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_21_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_22_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_23_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_24_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_2_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_3_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_4_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_5_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_6_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_7_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_8_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_10colors_cat_eye_9_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_bottle_2_.jpg',
                    '/uploads/products/catalog/CATEYES_E_SERIES_10_SHADES_KIT_Video.mp4',
                ],
                'shades' => [
                    ['name' => 'Moonstone Shimmer', 'hex' => '#CFD8DC'],
                    ['name' => 'Golden Aureole', 'hex' => '#D4AF37'],
                    ['name' => 'Midnight Indigo', 'hex' => '#283593'],
                ],
                'sizes' => [
                    'Complete 10-Shade Set (15ml each)',
                ],
                'benefits' => [
                    'Ultra-Fine Rare-Earth Magnetic Particles',
                    'Fluid Velvet Movement',
                    'Smooth 60s LED Cure',
                    'Non-Yellowing Formula',
                ],
                'sort_order' => 30,
            ],
            [
                'title' => 'Récolte 208 Colors Master Salon Gel Polish Suite',
                'slug' => 'recolte-208-colors-master-salon-gel-polish-suite',
                'category' => 'Gel Polishes',
                'category_id' => $catMap['Gel Polishes'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 169,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => 'Complete salon master suite of 208 luxury shades with comprehensive color book & display charts',
                'description' => 'The magnum opus of Récolte Nails Paris. 208 opulent shades spanning runway nudes, sultry bordeaux, energetic neons, sophisticated pastels, and timeless crèmes. Comes complete with a hardcover collector swatch book and studio color charts.',
                'key_ingredients' => '100% Japanese Resin Base, Cosmetic Grade Optical Pigments, Non-Yellowing Stabilizers',
                'how_to_use' => '1. Prep natural nail and apply base coat; cure 60s. 2. Apply 1-2 thin coats of color; cure 60s per coat. 3. Seal with Récolte Top Coat; cure 60s.',
                'main_image' => '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors.jpg',
                'images' => [
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors_5_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors_6_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_book_with_bottle_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_book_with_bottle_1_.png',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_book_with_bottle_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_book_with_bottle_2_.png',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_chart_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_chart_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_chart_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_color_chart_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_effect_picture_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_effect_picture_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_effect_picture_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_effect_picture_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_effect_picture_5_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Original_Video.mp4',
                    '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors.mp4',
                ],
                'shades' => [
                    ['name' => 'Parisian Red', 'hex' => '#8C1D2F'],
                    ['name' => 'Haute Nude', 'hex' => '#D7B49E'],
                    ['name' => 'Atelier Noir', 'hex' => '#141414'],
                    ['name' => 'Porcelain Pink', 'hex' => '#F8E8E6'],
                    ['name' => 'Royal Navy', 'hex' => '#1A2A44'],
                ],
                'sizes' => [
                    '208 Shade Complete Studio Collection (15ml Bottles)',
                ],
                'benefits' => [
                    '208 Full Spectrum Designer Colors',
                    'Includes Deluxe Bound Swatch Book',
                    '1-Coat Maximum Opacity',
                    'Zero Shrinkage & 4-Week Wear',
                ],
                'sort_order' => 31,
            ],
            [
                'title' => 'Récolte 150 Shades Classic Gel Polish Luxury Collection',
                'slug' => 'recolte-150-shades-classic-gel-polish-luxury-collection',
                'category' => 'Gel Polishes',
                'category_id' => $catMap['Gel Polishes'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 176,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => '150-color prestige salon collection curated for bridal, fashion & editorial nail design',
                'description' => 'Curated by Parisian colorists, the 150-Shade Collection offers a comprehensive palette tailored for luxury salons and discerning artists. Smooth buttery application ensures streak-free coverage in a single stroke.',
                'key_ingredients' => 'Ethical Acrylate Oligomer, Pure Organic Colorants, Low-Odor Photoinitiators',
                'how_to_use' => '1. Apply base coat and cure 60s. 2. Apply 2 thin coats of gel polish, curing each for 60s. 3. Finish with high-gloss top coat.',
                'main_image' => '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors.jpg',
                'images' => [
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_150-colors-set_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_150-colors-set_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_150-colors-set_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_150-colors-set_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_150-colors-set_5_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_150-colors-set_6_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_150_SHADES_KIT_Recolte-150_colors.mp4',
                ],
                'shades' => [
                    ['name' => 'Crimson Dahlia', 'hex' => '#9B1B30'],
                    ['name' => 'French Vanilla', 'hex' => '#F5EBE6'],
                    ['name' => 'Muted Mauve', 'hex' => '#A27082'],
                ],
                'sizes' => [
                    '150-Piece Master Salon Box (15ml each)',
                ],
                'benefits' => [
                    '150 Trend-Forward Shades',
                    'Precision Curved Ergonomic Brush',
                    'High Gloss Mirror Reflection',
                    'Low-Odor Eco Formula',
                ],
                'sort_order' => 32,
            ],
            [
                'title' => 'Récolte 96 Shades Signature Gel Polish Set',
                'slug' => 'recolte-96-shades-signature-gel-polish-set',
                'category' => 'Gel Polishes',
                'category_id' => $catMap['Gel Polishes'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 183,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => '96 runway-inspired signature shades engineered for salon artists and bespoke manicures',
                'description' => 'The quintessential Récolte signature collection. 96 indispensable shades engineered for high pigment density, self-leveling performance, and seamless blending. Packaged in our iconic gold-accented salon box.',
                'key_ingredients' => 'Pure Japanese Resin, Concentrated Mineral Pigments, Anti-Fading Stabilizers',
                'how_to_use' => '1. Apply base coat and cure. 2. Apply 1-2 coats of Signature 96 gel polish. 3. Cure 60s. 4. Seal with diamond top coat.',
                'main_image' => '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors.jpg',
                'images' => [
                    '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_96_SHADES_KIT_Recolte-96_colors.mp4',
                ],
                'shades' => [
                    ['name' => 'Silk Peony', 'hex' => '#D8A47F'],
                    ['name' => 'Berry Glaze', 'hex' => '#662249'],
                    ['name' => 'Café Crème', 'hex' => '#B8977E'],
                ],
                'sizes' => [
                    '96 Shades Collector Trunk (15ml each)',
                ],
                'benefits' => [
                    '96 Core Salon Tones',
                    'Self-Leveling Viscosity',
                    'Zero Streakiness or Bubbles',
                    'Fade-Proof Pigments',
                ],
                'sort_order' => 33,
            ],
            [
                'title' => 'Récolte 60 Shades Prestige Gel Polish Kit (R2 Series)',
                'slug' => 'recolte-60-shades-prestige-gel-polish-kit-r2-series',
                'category' => 'Gel Polishes',
                'category_id' => $catMap['Gel Polishes'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 190,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => '60-shade modern edition salon set featuring contemporary earth, pastel & jewel tones',
                'description' => 'The R2 Series introduces 60 cutting-edge contemporary nuances, featuring earthy terracotta, muted sage, dusty rose, and midnight jewel tones designed for modern salon aesthetics.',
                'key_ingredients' => 'Eco-Polymer Gel Formula, Natural Earth Tone Pigments, Advanced UV Initiators',
                'how_to_use' => '1. Base coat & cure 60s. 2. Apply 2 thin coats of R2 color, curing 60s each. 3. Seal with top coat.',
                'main_image' => '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_Recolte-60_colors.jpg',
                'images' => [
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_Recolte-60_colors.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_New_60-Colors-Set_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_New_60-Colors-Set_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_New_60-Colors-Set_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_New_60-Colors-Set_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_Recolte-60_colors_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_Recolte-60_colors_2_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_Recolte-60_colors_3_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_Recolte-60_colors_4_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R2_60_SHADES_KIT_video_for_New-60-Colors-Set.mp4',
                ],
                'shades' => [
                    ['name' => 'Matcha Mousse', 'hex' => '#99A882'],
                    ['name' => 'Terracotta Rose', 'hex' => '#C27D6B'],
                    ['name' => 'Slate Grey', 'hex' => '#707780'],
                ],
                'sizes' => [
                    '60 Shades Presentation Box (15ml each)',
                ],
                'benefits' => [
                    'Modern Aesthetic Palette',
                    'Optimized Viscosity for Fast Application',
                    'High Scratch Resistance',
                    'Professional Color Card Included',
                ],
                'sort_order' => 34,
            ],
            [
                'title' => 'Récolte 60 Shades Essential Gel Polish Kit (R1 Series)',
                'slug' => 'recolte-60-shades-essential-gel-polish-kit-r1-series',
                'category' => 'Gel Polishes',
                'category_id' => $catMap['Gel Polishes'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 197,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => '60 essential foundation shades providing the backbone for every professional nail studio',
                'description' => 'The foundation of every salon manicure. 60 essential staples covering French whites, translucent nudes, primary brights, and deep classic reds that clients request daily.',
                'key_ingredients' => 'High Viscosity Salon Oligomers, Cosmetic Colorants, UV Protection Factors',
                'how_to_use' => '1. Apply base coat; cure 60s. 2. Apply 2 coats of R1 shade; cure 60s each. 3. Top coat seal.',
                'main_image' => '/uploads/products/catalog/GEL_POLISHES_R1_60_SHADES_KIT_60-colors-set_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/GEL_POLISHES_R1_60_SHADES_KIT_60-colors-set_1_.jpg',
                    '/uploads/products/catalog/GEL_POLISHES_R1_60_SHADES_KIT_60-colors-set_2_.jpg',
                    '/videos/products/product-reel-1.mp4',
                ],
                'shades' => [
                    ['name' => 'Classic Nude', 'hex' => '#DEB887'],
                    ['name' => 'Scarlet Red', 'hex' => '#B22222'],
                    ['name' => 'Soft Ivory', 'hex' => '#FFFFF0'],
                ],
                'sizes' => [
                    '60-Piece Essential Set (15ml each)',
                ],
                'benefits' => [
                    'Most Requested Salon Shades',
                    'Seamless Creamy Consistency',
                    'Flawless 60s UV/LED Cure',
                    'Chip-Proof Longevity',
                ],
                'sort_order' => 35,
            ],
            [
                'title' => 'Récolte Velvet Matte Top Coat',
                'slug' => 'recolte-velvet-matte-top-coat',
                'category' => 'Matte Top Coat',
                'category_id' => $catMap['Matte Top Coat'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.95,
                'reviews_count' => 204,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Non-wipe cashmere matte finish transforming any glossy gel into sophisticated velvet',
                'description' => 'Récolte Velvet Matte Top Coat instantly imparts an ultra-chic, cashmere-soft tactile feel with zero glare. Formulated with non-wipe technology and anti-staining polymers to keep light colors pristine without yellowing or scuffing.',
                'key_ingredients' => 'Matte Silica Polyurethane, Anti-Yellowing Resins, Hydrophobic Surface Agents',
                'how_to_use' => '1. Complete your gel color application. 2. Brush a generous coat of Velvet Matte Top Coat over the nail. 3. Cure for 60 seconds under LED lamp. No wiping required.',
                'main_image' => '/uploads/products/catalog/MATTE_COAT_matte_top_coat_1_.png',
                'images' => [
                    '/uploads/products/catalog/MATTE_COAT_matte_top_coat_1_.png',
                    '/uploads/products/catalog/MATTE_COAT_matte_top_coat_2_.png',
                    '/uploads/products/catalog/MATTE_COAT_matte_top_coat_3_.png',
                    '/uploads/products/catalog/MATTE_COAT_matte_top_coat_4_.png',
                    '/uploads/products/catalog/MATTE_COAT_white_bottle_1_.JPG',
                    '/videos/products/product-reel-1.mp4',
                ],
                'shades' => [
                    ['name' => 'Velvet Frosted Matte', 'hex' => '#E8E4DF'],
                ],
                'sizes' => [
                    '15ml Studio Bottle',
                    '30ml Refill',
                ],
                'benefits' => [
                    'Soft-Touch Cashmere Matte Feel',
                    'Non-Wipe Instant Matte Formula',
                    'Anti-Stain & Anti-Scratch Protection',
                    'No White Haze or Streaking',
                ],
                'sort_order' => 36,
            ],
            [
                'title' => 'Récolte Molten Mirror Metallic Gel',
                'slug' => 'recolte-molten-mirror-metallic-gel',
                'category' => 'Metallic Gel',
                'category_id' => $catMap['Metallic Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 126,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'High-sheen liquid chrome metallic gel for liquid metal accents & mirror linework',
                'description' => 'A revolutionary liquid metal gel that cures to a true mirror shine without chrome powder or rubbing. Perfect for 3D metallic drips, French tips, frame lines, and baroque embellishments.',
                'key_ingredients' => 'Suspended Aluminum Flake Micro-Pigments, Mirror Reflective Resin, UV Cure Polymers',
                'how_to_use' => '1. Use a detail brush to paint metallic lines over cured gel. 2. Allow 5 seconds for self-leveling to reach full mirror reflection. 3. Cure 60s under LED. 4. Seal with Top Coat.',
                'main_image' => '/uploads/products/catalog/METALLIC_GEL_Metallic_Gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/METALLIC_GEL_Metallic_Gel_1_.jpg',
                    '/uploads/products/catalog/METALLIC_GEL_Metallic_Gel_2_.jpg',
                    '/uploads/products/catalog/METALLIC_GEL_Metallic_Gel_3_.jpg',
                    '/uploads/products/catalog/METALLIC_GEL_Metallic_Gel_4_.jpg',
                    '/uploads/products/catalog/METALLIC_GEL_Metallic_Gel_5_.jpg',
                    '/videos/products/product-reel-1.mp4',
                ],
                'shades' => [
                    ['name' => 'Liquid Silver Chrome', 'hex' => '#D9D9D9'],
                    ['name' => 'Molten Gold', 'hex' => '#E5B869'],
                    ['name' => 'Rose Gold Bronze', 'hex' => '#C98D7B'],
                ],
                'sizes' => [
                    '8g Precision Pot',
                    '15g Studio Pot',
                ],
                'benefits' => [
                    'Liquid Mirror Chrome Finish',
                    'Smooth Flow for Fine Lines',
                    'Does Not Oxidize or Tarnish',
                    'Cures Dry With Zero Chrome Powder Mess',
                ],
                'sort_order' => 37,
            ],
            [
                'title' => 'Récolte Clear Blending & Mixing Gel',
                'slug' => 'recolte-clear-blending-mixing-gel',
                'category' => 'Mixing Gel',
                'category_id' => $catMap['Mixing Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 133,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Multi-purpose crystal dilution gel for custom glitter pastes, ombré shading & pigment blending',
                'description' => 'A must-have medium in every nail artist kit. Seamlessly thins opaque gel polishes for sheer jelly and glazed glass effects, suspends loose glitters without sinking, and creates flawless gradient ombré transitions.',
                'key_ingredients' => 'Ultra-Clear Acrylate Diluent, Viscosity Modifiers, Neutral Photo-Stabilizers',
                'how_to_use' => '1. Mix with gel polish or loose glitter on a palette until desired transparency is reached. 2. Apply with brush. 3. Cure 60s.',
                'main_image' => '/uploads/products/catalog/MIXING_GEL_mixing_gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/MIXING_GEL_mixing_gel_1_.jpg',
                    '/uploads/products/catalog/MIXING_GEL_mixing_gel_2_.jpg',
                    '/uploads/products/catalog/MIXING_GEL_mixing_gel_3_.jpg',
                    '/uploads/products/catalog/MIXING_GEL_mixing_gel_1_.mp4',
                ],
                'shades' => [
                    ['name' => 'Crystal Clear Diluter', 'hex' => '#FFFFFF'],
                ],
                'sizes' => [
                    '15ml Bottle',
                    '30ml Artist Jar',
                ],
                'benefits' => [
                    'Seamlessly Blends Glitters & Pigments',
                    'Maintains Gel Viscosity & Curing Speed',
                    'Ideal for Ombré & Gradient Nails',
                    'Zero Cloudiness or Yellowing',
                ],
                'sort_order' => 38,
            ],
            [
                'title' => 'Récolte Fine Art Nail Painting Gel',
                'slug' => 'recolte-fine-art-nail-painting-gel',
                'category' => 'Painting Gel',
                'category_id' => $catMap['Painting Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 140,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Extra-dense micro-pigmented painting gel for intricate linework, portraits & French smiles',
                'description' => 'Crafted specifically for nail artists who demand extreme detail. Ultra-high pigment concentration allows paper-thin lines with 100% opacity that do not spread, bleed, or shrink before curing.',
                'key_ingredients' => 'Micronized Artist-Grade Pigments, Non-Drip Structural Resins, Optical Stabilizers',
                'how_to_use' => '1. Pick up a minute bead with a fine detail brush (size 00 or 000). 2. Draw crisp linework or art onto matte or cleansed surface. 3. Cure 60s.',
                'main_image' => '/uploads/products/catalog/PAINTING_GEL_Nail_Art_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/PAINTING_GEL_Nail_Art_1_.jpg',
                    '/uploads/products/catalog/PAINTING_GEL_Nail_Art_3_.jpg',
                    '/uploads/products/catalog/PAINTING_GEL_Nail_Art_4_.jpg',
                    '/uploads/products/catalog/PAINTING_GEL_Nail_Art_5_.jpg',
                    '/uploads/products/catalog/PAINTING_GEL_Nail_Art_6_.jpg',
                    '/uploads/products/catalog/PAINTING_GEL_Video_for_nail_art_gel.mp4',
                ],
                'shades' => [
                    ['name' => 'Pure White Art', 'hex' => '#FFFFFF'],
                    ['name' => 'Obsidian Black', 'hex' => '#000000'],
                    ['name' => 'Imperial Crimson', 'hex' => '#8B0000'],
                ],
                'sizes' => [
                    '12g Artist Jar Set',
                    'Individual 8g Pots',
                ],
                'benefits' => [
                    'Single-Stroke Ultra Pigmentation',
                    'Does Not Bleed or Shrink',
                    'Razor-Sharp Precision Lines',
                    'Tack-Free Finish',
                ],
                'sort_order' => 39,
            ],
            [
                'title' => 'Récolte Platinum Foil & Glitter Gel',
                'slug' => 'recolte-platinum-foil-glitter-gel',
                'category' => 'Platinum Gel',
                'category_id' => $catMap['Platinum Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 147,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Heavyweight crushed foil and diamond micro-glitter gel for opulent starlight sparkle',
                'description' => 'Saturated with crushed platinum leaf and multi-cut diamond glitters, this gel provides dazzling multidimensional brilliance that catches every ray of light. One coat yields intense, luxurious coverage.',
                'key_ingredients' => 'Crushed Optical Platinum Foil, Multi-Angle Holographic Glitter, Polyacrylate Gel Base',
                'how_to_use' => '1. Apply base coat. 2. Paint 1-2 coats of Platinum Gel using a flat gel brush. 3. Cure 60s. 4. Seal with high-gloss top coat.',
                'main_image' => '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_1_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_3_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_4_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_5_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_6_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_7_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_8_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Nails_Art_Gel_1_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Nails_Art_Gel_2_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Nails_Art_Gel_3_.jpg',
                    '/uploads/products/catalog/PLATINUM_GEL_Platinum_Gel_1_.mp4',
                ],
                'shades' => [
                    ['name' => 'Pure Diamond Platinum', 'hex' => '#E0E0E0'],
                    ['name' => 'Champagne Starlight', 'hex' => '#EAD7A6'],
                    ['name' => 'Rosé Platinum', 'hex' => '#E5B2B8'],
                ],
                'sizes' => [
                    '8g Deluxe Diamond Pot',
                    '15g Studio Pot',
                ],
                'benefits' => [
                    'High Concentration Crushed Platinum Foils',
                    'Blinding Diamond Faceted Reflection',
                    'Dense Coverage in One Layer',
                    'Smooth Surface Once Sealed',
                ],
                'sort_order' => 40,
            ],
            [
                'title' => 'Récolte Acryl-Gel Hybrid Polygel',
                'slug' => 'recolte-acryl-gel-hybrid-polygel',
                'category' => 'Polygel',
                'category_id' => $catMap['Polygel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 154,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Odorless hybrid acrylic-gel extension formula offering effortless control and unbreakable durability',
                'description' => 'Combining the rock-solid strength of acrylics with the lightweight flexibility and odorless nature of hard gels. Stays precisely where placed until manipulated with slip solution, allowing beginners and pros to sculpt perfect extensions.',
                'key_ingredients' => 'Polymerized Acrylic Urethane, Micro-Particle Fillers, Light-Activated Photo-Initiators',
                'how_to_use' => '1. Squeeze tube and slice bead with polygel spatula. 2. Place into dual form or onto prepped nail. 3. Dampen brush in slip solution and sculpt. 4. Cure 60s under LED lamp. 5. Pop off dual form and file.',
                'main_image' => '/uploads/products/catalog/POLYGEL_poly_gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/POLYGEL_poly_gel_1_.jpg',
                    '/uploads/products/catalog/POLYGEL_poly_gel_1_.png',
                    '/uploads/products/catalog/POLYGEL_poly_gel_2_.jpg',
                    '/videos/products/product-reel-1.mp4',
                ],
                'shades' => [
                    ['name' => 'Clear Glass', 'hex' => '#F2F2F2'],
                    ['name' => 'Natural Cover Pink', 'hex' => '#E5AFB2'],
                    ['name' => 'Milky White', 'hex' => '#FAF5F2'],
                ],
                'sizes' => [
                    '60g Squeeze Tube',
                    '30g Starter Tube',
                ],
                'benefits' => [
                    'Lighter Than Acrylics, Stronger Than Hard Gels',
                    'No Liquid Monomer Odor',
                    'Unlimited Working Time Before Curing',
                    'Dual-Form & Paper Form Compatible',
                ],
                'sort_order' => 41,
            ],
            [
                'title' => 'Récolte Acid-Free Dehydrating Bond Primer',
                'slug' => 'recolte-acid-free-dehydrating-bond-primer',
                'category' => 'Primer',
                'category_id' => $catMap['Primer'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 161,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Gentle non-acid natural nail dehydrator and bonding agent ensuring 0% lifting',
                'description' => 'Essential preparation for any long-wearing manicure. Quickly evaporates natural surface oils and moisture from the nail plate while depositing a sticky molecular bonding film that locks gel base coat to keratin.',
                'key_ingredients' => 'Ethyl Acetate Dehydrating Complex, Molecular Adhesion Promoters, Panthenol Fortifier',
                'how_to_use' => '1. Gently buff natural nail surface and wipe with cleanser. 2. Brush a sparing amount of Primer across the nail plate. 3. Air dry for 30-40 seconds until slightly tacky. 4. Apply Base Coat.',
                'main_image' => '/uploads/products/catalog/PRIMER_primer.jpg',
                'images' => [
                    '/uploads/products/catalog/PRIMER_primer.jpg',
                    '/videos/products/product-reel-1.mp4',
                ],
                'shades' => [
                    ['name' => 'Clear Prep Bond', 'hex' => '#F7F5F0'],
                ],
                'sizes' => [
                    '15ml Glass Bottle with Precision Applicator',
                ],
                'benefits' => [
                    'Removes Surface Moisture & Natural Oils',
                    'Creates Double-Sided Adhesive Film',
                    'Acid-Free & Non-Damaging to Natural Nails',
                    'Air Dries in 30 Seconds',
                ],
                'sort_order' => 42,
            ],
            [
                'title' => 'Récolte 24 Flash Reflective Glitter Gel Polish',
                'slug' => 'recolte-24-flash-reflective-glitter-gel-polish',
                'category' => 'Reflective Polish',
                'category_id' => $catMap['Reflective Polish'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 168,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Hypnotic light-activated diamond flash disco gel polish bursting with brilliant luminescence',
                'description' => 'Featuring advanced retroreflective crystal beads that capture and bounce direct light. Appears as a classy subtle micro-shimmer under normal daytime ambient lighting, and explodes into blinding diamond sparkle under camera flashes and club lights.',
                'key_ingredients' => 'Reflective Glass Micro-Prisms, Highly Purified Gel Resin, Anti-Settling Suspension Fluid',
                'how_to_use' => '1. Apply base coat & cure. 2. Apply 1-2 coats of Flash Reflective Polish. 3. Cure 60s per coat. 4. Seal with Récolte Diamond Top Coat.',
                'main_image' => '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_1_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_3_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_4_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_5_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_6_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash_7_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_bottle_2_.jpg',
                    '/uploads/products/catalog/REFLECTIVE_POLISH_Recolte-24_Flash.mp4',
                ],
                'shades' => [
                    ['name' => 'Flash Diamond Silver', 'hex' => '#E8E8E8'],
                    ['name' => 'Flash Ruby Noir', 'hex' => '#8C1D40'],
                    ['name' => 'Flash Midnight Spark', 'hex' => '#1E2340'],
                ],
                'sizes' => [
                    '24 Shades Luxury Suite (15ml each)',
                    'Single 15ml Bottle',
                ],
                'benefits' => [
                    'Reflects Direct Flash with Intense Diamond Glow',
                    'Subtle Shimmer in Daytime, Blinding Sparkle at Night',
                    'Smooth Gliding Self-Leveling Formula',
                    'Long-Lasting 4+ Weeks Wear',
                ],
                'sort_order' => 43,
            ],
            [
                'title' => 'Récolte No-Wipe Precision Rhinestone Gel',
                'slug' => 'recolte-no-wipe-precision-rhinestone-gel',
                'category' => 'Rhinestone Gel',
                'category_id' => $catMap['Rhinestone Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 175,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Industrial-strength no-wipe adhesive gel securing crystals, 3D charms and metal studs permanently',
                'description' => 'Say goodbye to missing gems and cloudy crystals. Formulated with thick cement-like viscosity and no-wipe technology, this gel secures heavy alloy charms, Swarovski crystals, and pearls without budging for a month or more.',
                'key_ingredients' => 'High Tensile Cyano-Acrylate Copolymer, Elastic Optical Gel Matrix, UV Curative Catalysts',
                'how_to_use' => '1. Apply a dot or bead of Rhinestone Gel where charm or crystal will sit. 2. Place crystal and gently press into position. 3. Cure 60-90s under UV/LED lamp. No wiping required.',
                'main_image' => '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe.jpg',
                'images' => [
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_2_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_3_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_4_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_5_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_6_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_7_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_8_.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_soft_tube_rhinestone_gel.jpg',
                    '/uploads/products/catalog/RHINESTONE_GEL_Rhinestone_Gel-No_Wipe_1_.mp4',
                ],
                'shades' => [
                    ['name' => 'Crystal Clear Cement', 'hex' => '#FFFFFF'],
                ],
                'sizes' => [
                    '15ml Needle-Tip Precision Tube',
                    '20g Studio Jar',
                ],
                'benefits' => [
                    'No-Wipe Tack-Free Formula',
                    'Ultra-High Viscosity Holds Heavy Charms in Place',
                    'Zero Clouding on Swarovskis & Gem Facets',
                    'Shock-Resistant 4+ Weeks Adhesion',
                ],
                'sort_order' => 44,
            ],
            [
                'title' => 'Récolte 5-in-1 Fortifying Rubber Base Coat',
                'slug' => 'recolte-5-in-1-fortifying-rubber-base-coat',
                'category' => 'Rubber Base',
                'category_id' => $catMap['Rubber Base'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 182,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Multifunctional rubberized elastic base for apex reinforcement, natural nail repair & strength',
                'description' => 'A resilient rubberized base gel that bends with the natural nail rather than cracking. Fills deep ridges, repairs split nails, builds structural apexes, and provides a translucent milky or nude color overlay in one simple step.',
                'key_ingredients' => 'Rubberized Elastic Monomer Blend, Calcium & Keratin Reinforcers, Natural Mineral Tints',
                'how_to_use' => '1. Prep and prime natural nail. 2. Apply a thin slip layer of Rubber Base, followed by a small bead to build apex. 3. Flip hand upside down for 5s to self-level. 4. Cure 60s under LED lamp.',
                'main_image' => '/uploads/products/catalog/RUBBER_BASE_5-in-1_Rubber_Base_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/RUBBER_BASE_5-in-1_Rubber_Base_1_.jpg',
                    '/uploads/products/catalog/RUBBER_BASE_5-in-1_Rubber_Base_2_.jpg',
                    '/uploads/products/catalog/RUBBER_BASE_5-in-1_Rubber_Base_3_.jpg',
                    '/uploads/products/catalog/RUBBER_BASE_5in1_rubber_base.jpg',
                    '/uploads/products/catalog/RUBBER_BASE_5in1_rubber_base.mp4',
                ],
                'shades' => [
                    ['name' => 'Sheer Nude Rose', 'hex' => '#E7BCB6'],
                    ['name' => 'Milky Base', 'hex' => '#F8F4F0'],
                    ['name' => 'Clear Elastic', 'hex' => '#ECE5DF'],
                ],
                'sizes' => [
                    '15ml Salon Bottle',
                    '30ml Pro Refill',
                ],
                'benefits' => [
                    '5-in-1: Base, Builder, Apex Leveler, Strengthener & Color',
                    'Bends with Natural Nail to Prevent Cracking',
                    'Ideal for Weak, Bitten or Ridged Nails',
                    'Self-Levels in Seconds',
                ],
                'sort_order' => 45,
            ],
            [
                'title' => 'Récolte Solid Glue Gel for Full Cover Tips',
                'slug' => 'recolte-solid-glue-gel-for-full-cover-tips',
                'category' => 'Solid Glue Gel',
                'category_id' => $catMap['Solid Glue Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 189,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Solid non-stick putty gel for applying soft gel tips and press-ons with zero bubbles or spillage',
                'description' => 'The modern revolution in press-on and soft gel tip application. Solid putty texture can be rolled with fingers, placed inside the tip, and pressed onto the natural nail without any sticky liquid flooding the cuticle or creating air bubbles.',
                'key_ingredients' => 'Solidified Acrylate Polymer Matrix, High-Adhesion Tackifiers, Photo-Initiating Resins',
                'how_to_use' => '1. Prep natural nail and apply primer. 2. Scoop a small sphere of Solid Glue Gel into the base of the full-cover tip. 3. Press firmly from cuticle to free edge, squeezing out all air. 4. Flash cure 10s, then full cure 60s.',
                'main_image' => '/uploads/products/catalog/SOLID_GLUE_GEL_Solid_Glue_Gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/SOLID_GLUE_GEL_Solid_Glue_Gel_1_.jpg',
                    '/uploads/products/catalog/SOLID_GLUE_GEL_Solid_Glue_Gel_2_.jpg',
                    '/uploads/products/catalog/SOLID_GLUE_GEL_Solid_Glue_Gel_3_.jpg',
                    '/videos/products/product-reel-1.mp4',
                ],
                'shades' => [
                    ['name' => 'Crystal Clear Solid Glue', 'hex' => '#FFFFFF'],
                ],
                'sizes' => [
                    '15g Solid Pot',
                    '25g Studio Pot',
                ],
                'benefits' => [
                    'Solid Putty Form - Does Not Run into Cuticles',
                    'Adjust Tip Position Freely Before UV Cure',
                    'Zero Air Bubbles Under Clear Extension Tips',
                    'Holds Firm for 30+ Days',
                ],
                'sort_order' => 46,
            ],
            [
                'title' => 'Récolte Matrix Elastic Line Spider Gel',
                'slug' => 'recolte-matrix-elastic-line-spider-gel',
                'category' => 'Spider Gel',
                'category_id' => $catMap['Spider Gel'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.9,
                'reviews_count' => 196,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Super-elastic matrix gel that stretches into razor-thin straight lines and geometric nail art',
                'description' => 'With extreme tensile elasticity, Récolte Spider Gel pulls out of the pot like a spider web and drapes across the nail in impossibly straight geometric lines, french edges, and abstract cage designs without snapping.',
                'key_ingredients' => 'Elastic Polyurethane Matrix, High Viscosity Stabilizers, Concentrated Carbon/Titanium Pigments',
                'how_to_use' => '1. Dip a dotting tool or fine brush into the gel and lift upwards to draw an elastic thread. 2. Lay the thread across the nail in your desired pattern. 3. Clean sidewalls and cure 60s. 4. Seal with Top Coat.',
                'main_image' => '/uploads/products/catalog/SPIDER_GEL_Spider_Gel_1_.jpg',
                'images' => [
                    '/uploads/products/catalog/SPIDER_GEL_Spider_Gel_1_.jpg',
                    '/uploads/products/catalog/SPIDER_GEL_Spider_Gel_3_.jpg',
                    '/uploads/products/catalog/SPIDER_GEL_Spider_Gel_4_.jpg',
                    '/uploads/products/catalog/SPIDER_GEL_Spider_Gel_5_.jpg',
                    '/uploads/products/catalog/SPIDER_GEL_Spider_Gel_1_.mp4',
                ],
                'shades' => [
                    ['name' => 'Matrix White', 'hex' => '#FFFFFF'],
                    ['name' => 'Matrix Black', 'hex' => '#111111'],
                    ['name' => 'Matrix Gold', 'hex' => '#D4AF37'],
                ],
                'sizes' => [
                    '6g Precision Pot Duo (Black & White)',
                    'Individual 6g Pots',
                ],
                'benefits' => [
                    'Ultra-Elastic High Viscosity Spider Formula',
                    'Draws Perfectly Straight Lines with Dotting Tool',
                    'Zero Breakage Mid-Air',
                    'Deep Pigment with No Shrinking',
                ],
                'sort_order' => 47,
            ],
            [
                'title' => 'Récolte Long Wear No Wipe Top Coat',
                'slug' => 'recolte-long-wear-no-wipe-top-coat',
                'category' => 'Top Coats',
                'category_id' => $catMap['Top Coats'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.98,
                'reviews_count' => 203,
                'is_bestseller' => true,
                'is_active' => true,
                'tagline' => 'Super Bright Luxury Glassy Surface with Anti-Scratch & 4-Week Mirror Durability',
                'description' => 'Engineered with tempered glass molecular structure, this no-wipe top coat forms an impenetrable high-luster shield. Repels micro-scratches from keys and abrasive contact, keeping manicures gleaming wet for over a month.',
                'key_ingredients' => 'Tempered Siloxane Polymer, Optical Clarifying Monomers, Non-Wipe Photo-Catalysts',
                'how_to_use' => '1. Apply after your gel color application. 2. Cap free edge and coat nail evenly. 3. Cure 60 seconds under LED lamp. No alcohol wipe needed.',
                'main_image' => '/uploads/products/catalog/TOP_COATS_top.png',
                'images' => [
                    '/uploads/products/catalog/TOP_COATS_top.png',
                    '/uploads/products/catalog/TOP_COATS_top_coat_1_.png',
                    '/uploads/products/catalog/TOP_COATS_top_coat_2_.png',
                    '/uploads/products/catalog/TOP_COATS_top..png',
                    '/uploads/products/catalog/TOP_COATS_white_bottle_1_.JPG',
                    '/uploads/products/catalog/TOP_COATS_white_bottle_2_.JPG',
                    '/uploads/products/catalog/TOP_COATS_top_coat.mp4',
                ],
                'shades' => [
                    ['name' => 'Tempered Crystal Gloss', 'hex' => '#FFFFFF'],
                ],
                'sizes' => [
                    '15ml Studio Bottle',
                    '30ml Master Refill',
                ],
                'benefits' => [
                    'Diamond Tempered Scratch-Proof Finish',
                    'Non-Wipe Instant Mirror Gloss',
                    'Anti-Yellowing UV Inhibitors',
                    'Keeps Gel Manicure Glossy for 35+ Days',
                ],
                'sort_order' => 48,
            ],
            [
                'title' => 'Récolte 6-in-1 Diamond Hard Top Coat',
                'slug' => 'recolte-6-in-1-diamond-hard-top-coat',
                'category' => '6-in-1 Top Coat',
                'category_id' => $catMap['6-in-1 Top Coat'] ?? null,
                'price' => null,
                'original_price' => null,
                'rating' => 4.95,
                'reviews_count' => 125,
                'is_bestseller' => false,
                'is_active' => true,
                'tagline' => 'Multifunctional reinforced hard seal top coat for apex overlay, chrome buffing, and extreme durability',
                'description' => 'The ultimate all-in-one salon weapon. Serves as a reinforced hard gel top coat, apex building overlay, encapsulating gel for glitters and dried florals, mirror chrome powder rubbing base, diamond sealer, and nail fortifier.',
                'key_ingredients' => 'Hard Glass-Resin Polymer, High-Viscosity Capping Monomers, Optical Glaze Fortifiers',
                'how_to_use' => '1. Apply as hard sealing top coat, or cure 30s to use as the perfect base for mirror chrome powder burnishing. 2. Full cure 60 seconds. Non-wipe formula.',
                'main_image' => '/uploads/products/catalog/6_IN_1_TOP_COAT_6-in-1_Top_Coat.jpg',
                'images' => [
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_6-in-1_Top_Coat.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_02.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_03.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_04.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_05-1.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_05.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_06.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_07.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_08.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_09.jpg',
                    '/uploads/products/catalog/6_IN_1_TOP_COAT_6-in-1_Top_Coat_video_demonstration.mp4',
                ],
                'shades' => [
                    ['name' => 'Reinforced Diamond Glaze', 'hex' => '#FFFFFF'],
                ],
                'sizes' => [
                    '15ml Precision Bottle',
                    '30ml Salon Refill',
                ],
                'benefits' => [
                    '6-in-1: Hard Top, Chrome Base, Apex Seal, Encapsulation, Scratch Armor & High Gloss',
                    'Reinforces Soft Nails with Hard Gel Strength',
                    'Super Mirror Luster with No Scuffs',
                    'Optimal Base for Chrome Powder Rubbing',
                ],
                'sort_order' => 49,
            ],
        ];

        // Replace current products: clean old products not in new dataset or update/create
        $newSlugs = array_column($products, 'slug');
        Product::whereNotIn('slug', $newSlugs)->delete();

        foreach ($products as $prod) {
            Product::updateOrCreate(['slug' => $prod['slug']], $prod);
        }

        // ── 5. PAGE CONTENTS (HOME EDITABLE SECTIONS) ──
        $homeHero = [
            'bg_image' => '/images/banners/hero-slide-main-recolte.png',
            'brand_title' => 'Recolte',
            'brand_trademark' => '®',
            'sub_descriptor' => 'NAILS • BEAUTY • YOU',
            'script_line' => 'Create • Express • Shine',
            'subtitle' => 'Premium Nail Products for Professionals & Enthusiasts',
            'cta_text' => 'SHOP NOW',
            'cta_url' => '/products',
            'metric_number' => '4.9★',
            'metric_text' => 'Your Nails Deserve the Best. Explore our Handcrafted Salon Formulations Today!',
        ];
        PageContent::setSection('home', 'hero', $homeHero);

        $homePillars = [
            'badge' => 'Nails by Récolte • Paris',
            'title' => 'Unlock Your Best Nails: Trusted by Nail Enthusiasts',
            'card1_num' => '01 / ATELIER FORMULATION',
            'card1_title' => 'Japanese Gel Craftsmanship',
            'card1_desc' => 'Every formulation is hand-layered with salon-grade Japanese gel resins, guaranteeing true-to-life luster, optical chrome effects, and chip-free durability that withstands daily life.',
            'card1_image' => 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=600&q=80',
            'card2_num' => '02 / GENTLE HEALTH',
            'card2_title' => 'Zero Natural Nail Damage',
            'card2_desc' => 'Engineered for effortless removal without harsh drills or acetone damage, preserving your natural nail keratin bed intact.',
            'card2_image' => 'https://images.unsplash.com/photo-1599458356314-91ca8ca575c5?auto=format&fit=crop&w=600&q=80',
        ];
        PageContent::setSection('home', 'pillars', $homePillars);

        $homeRituals = [
            'badge' => 'RADIANT NAIL RITUALS',
            'title' => 'The Art of Parisian Nail Care',
            'subtitle' => 'Explore our complete suite of handcrafted luxury manicures, salon gel polishes, and organic botanical care.',
            'card1_title' => 'Gel Polishes',
            'card1_sub' => 'Master 208 shades suite',
            'card1_img' => '/uploads/products/catalog/GEL_POLISHES_208_colors_set_Recolte-208_colors.jpg',
            'card2_title' => 'Cat Eye Gels',
            'card2_sub' => 'Velvet magnetic depth',
            'card2_img' => '/uploads/products/catalog/CATEYES_A_SERIES_24_SHADES_KIT_Recolte-24_Cat_Eye_4_.jpg',
            'card3_title' => 'Builder Gels',
            'card3_sub' => 'Sculpting & apex overlays',
            'card3_img' => '/uploads/products/catalog/BUILDER_GEL_builder_gel_1_.jpg',
            'card4_title' => 'Top & Base Coats',
            'card4_sub' => 'Tempered mirror shield',
            'card4_img' => '/uploads/products/catalog/TOP_COATS_top_coat_1_.png',
            'editorial_quote' => 'Nails are the period at the end of the sentence. They complete the look.',
            'editorial_desc' => 'True beauty begins with nail health. Our dual-phase approach combines pure Japanese resins with fortifying care to deliver salon-perfect results without compromise.',
        ];
        PageContent::setSection('home', 'rituals', $homeRituals);

        $homePhilosophy = [
            'badge' => 'HAUTE ATELIER PHILOSOPHY',
            'title' => 'Timeless Nail Care. Ageless Beauty Starts Here.',
            'p1_title' => '100% Non-Toxic & HEMA-Free',
            'p1_desc' => 'Pure formulas free from harsh allergens, formaldehyde, and toluene to preserve natural nail bed vitality.',
            'p2_title' => 'High-Yield Salon Formulation',
            'p2_desc' => 'Crafted with premium salon resins and Japanese gels for 4+ weeks of chip-free wear.',
            'p3_title' => 'Precision Application',
            'p3_desc' => 'Ergonomic custom brushes and self-leveling viscosity ensuring flawless single-stroke coverage.',
        ];
        PageContent::setSection('home', 'philosophy', $homePhilosophy);

        $homeInstagram = [
            'badge' => 'PARISIAN NAIL COMMUNITY',
            'title' => 'Join Our Global Atelier Gallery',
            'subtitle' => 'Tag @recolte_gelpolish on Instagram with your Récolte manicures to be featured.',
            'btn_text' => 'Follow @recolte_gelpolish on Instagram ↗',
            'btn_url' => 'https://www.instagram.com/recolte_gelpolish/',
        ];
        PageContent::setSection('home', 'instagram', $homeInstagram);

        // ── 6. PAGE CONTENTS (ABOUT PAGE FULL DYNAMIC SECTIONS) ──
        $aboutStory = [
            'badge' => 'OUR ATELIER HERITAGE & VISION',
            'title' => 'Where Parisian Haute Couture Meets Organic Nail Science',
            'paragraphs' => [
                'Founded in Paris, Récolte Nails was born from a singular atelier obsession: creating salon-grade gel systems and organic nail formulations that enhance your elegance without ever compromising the health of your natural nail bed.',
                'Every product in our archives is meticulously engineered using Japanese salon gels, optical chrome pigments, and self-leveling polymers to guarantee 4+ weeks of chip-free, luminous wear.',
                'Our philosophy bridges the world of runway aesthetics with pure botanical care. From our revolutionary HEMA-free Japanese salon gels to tempered top coats, we ensure that salon glamour and natural nail wellness coexist seamlessly.'
            ],
            'stat1_num' => '4+ Weeks',
            'stat1_label' => 'Chip-Free Salon Wear',
            'stat2_num' => '100%',
            'stat2_label' => 'Organic & Non-Toxic Formulas',
            'stat3_num' => '120K+',
            'stat3_label' => 'Salon Products Delivered Worldwide',
            'stat4_num' => '0%',
            'stat4_label' => 'Natural Nail Damage Guarantee',
        ];
        PageContent::setSection('about', 'story', $aboutStory);

        $aboutPillars = [
            'p1_icon' => '🎨',
            'p1_title' => 'Japanese Gel Craftsmanship',
            'p1_desc' => 'Formulated with authentic Japanese salon gels, optical chrome, and high-refraction top coats for unmatched depth and strength.',
            'p2_icon' => '🌿',
            'p2_title' => '100% Non-Toxic & HEMA-Free',
            'p2_desc' => 'We reject harmful chemicals. Our formulations prioritize skin-friendly, hypoallergenic ingredients that protect your natural nail bed.',
            'p3_icon' => '✨',
            'p3_title' => 'Zero Damage Soak-Off',
            'p3_desc' => 'Gentle soak-off formulations that release cleanly without harsh drills or excessive filing.',
            'p4_icon' => '📐',
            'p4_title' => 'Professional Salon Grade',
            'p4_desc' => 'Tested and approved by master nail artists across Paris, Milan, and Tokyo for flawless daily performance.',
        ];
        PageContent::setSection('about', 'pillars', $aboutPillars);

        $aboutSteps = [
            'step1_num' => '01',
            'step1_title' => 'Precision Nail Preparation',
            'step1_desc' => 'Cleanse and dehydrate with Récolte Acid-Free Primer to create an optimal bonding anchor.',
            'step2_num' => '02',
            'step2_title' => 'Base & Apex Architecture',
            'step2_desc' => 'Apply Récolte Professional Base Coat or BIAB Liquid Builder to reinforce structure and curvature.',
            'step3_num' => '03',
            'step3_title' => 'Pure Pigment Infusion',
            'step3_desc' => 'Apply high-density Japanese gel polishes, magnetic cat-eye glazes, or fine art painting gels.',
            'step4_num' => '04',
            'step4_title' => 'Tempered Diamond Armor',
            'step4_desc' => 'Seal under Récolte High Gloss Tempered Top Coat or Velvet Matte for 35+ days of mirror protection.',
        ];
        PageContent::setSection('about', 'steps', $aboutSteps);
    }
}
